server:
   port: 8080
spring:
   security:
      basic:
         enabled: false
      user:
         name: admin
         password: 123456
   # Druid连接池配置，官方配置参考：https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter      
   datasource:
      url: jdbc:oracle:thin:@10.50.21.119:1521:orcl
      username: bireport
      password: Citic_20180911
      driver-class-name: oracle.jdbc.driver.OracleDriver
      druid:
         initial-size: 1 # 初始化大小，最小，最大
         min-idle: 3
         max-active: 20
         max-wait: 60000  # 配置获取连接等待超时的时间 单位毫秒
         time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
         min-evictable-idle-time-millis: 30000 # 配置一个连接在池中最小生存的时间，单位是毫秒
         validation-query: SELECT 1 FROM DUAL #测试连接
         test-while-idle: true #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
         test-on-borrow: false #获取连接时执行检测，建议关闭，影响性能
         test-on-return: false #归还连接时执行检测，建议关闭，影响性能
         pool-prepared-statements: true #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
         max-pool-prepared-statement-per-connection-size: 20 #开启poolPreparedStatements后生效
         filters: stat,wall,slf4j #配置扩展插件，常用的插件有:>stat:监控统计  log4j:日志  wall:防御sql注入
         filter:
            stat:
               log-slow-sql: true
               slow-sql-millis: 2000
         web-stat-filter: # Druid WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
            enabled: true
            url-pattern: '/*'
            exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
         stat-view-servlet: # Druid StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
            enabled: true
            url-pattern: '/druid/*'
            reset-enable: true
            login-username: 'admin'
            login-password: '123456'
            allow: 
            deny:

mybatis: #Mybatis配置,官方参考：http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/
  type-aliases-package: com.citic.datacenter.model
  mapper-locations: classpath*:mapper/*.xml

#logging:
#	config: classpath: log4j2-spring.xml